apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack-k8s.yml
    kompose.version: 1.5.0 (999278f)
  creationTimestamp: null
  labels:
    io.kompose.service: vote
  name: vote
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: vote
    spec:
      containers:
      - image: sakibj/vote_vote:cs553
        name: vote
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
