version: "3"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
  db:
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
  vote:
    image: sakibj/vote_vote:cs553
    ports:
      - "5000:80"
    depends_on:
      - redis
  result:
    image: sakibj/vote_result:cs553
    ports:
      - "5001:80"
    depends_on:
      - db
  worker:
    image: sakibj/vote_worker:cs553

volumes:
  db-data:
